org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Base Dependencies
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]

neo_version=21.1.219
neo_version_range=[21,)
loader_version_range=[4,)

# Mod Properties
mod_id=satchels
mod_name=Satchels
mod_version=1.0.0+alpha.6
mod_license=MIT

mod_group_id=net.vercte
mod_authors=Vercte
mod_description=another kind of inventory management

# Mod Support
curios_enabled=true
curios_version=9.5.1
curios_version_range=[9.2.0,)

jei_enabled=true
jei_version=19.27.0.340
